# Parameters for the workflow
# Assembly Mode: 'hybrid', 'denovo', or 'ref_guided'
assembly_mode: 'hybrid'

######################## Tool Presets ########################
# rnabloom2 presets:
#   ''      : Leave empty for ONT (default)
#   'lrpb'  : For PacBio
rnabloom2_preset: ''

# minimap2 presets (passed to -ax):
#   'map-ont' : Oxford Nanopore genomic reads (default)
#   'map-pb'  : PacBio CLR genomic reads
#   'map-hifi': PacBio HiFi/CCS genomic reads (v2.19+)
#   'lr:hq'   : Nanopore Q20 genomic reads (v2.27+)
minimap2_preset: 'map-ont'

######################## Filtering & Thresholds ########################
RUN_DE: true                # true or false (default: true)
fdr: 0.05                   # default 0.05
min_cpm: 0.5                # default 0.5
min_logfc: 2                # default 2
min_clip: 20                # default 20
min_gap: 7                  # default 7
min_match: '30,0.3'         # default '30,0.3'
splice_motif_mismatch: 1    # default 1
oarfish_num_bootstraps: 10  # default 10
gene_filter: NULL           # default NULL (e.g. "TP53,BRCA2")
var_filter: NULL            # default NULL (e.g. "DEL,INS")

# Paths to the input files (note: ${projectDir} refers to the directory containing main.nf)
code_base: "${projectDir}/modules/code_base"
cases_fastq_dir: './cases'
controls_fastq_dir: './controls'
trans_fasta: "${projectDir}/ref/chess3.0.fa"
tx_annotation: "${projectDir}/ref/chess3.0.gtf"
ann_info: "${projectDir}/ref/chess3.0.info"
tx2gene: "${projectDir}/ref/tx2gene.txt"
hg38_fasta: "${projectDir}/ref/hg38.fa"
hg38_splice_junctions: "${projectDir}/ref/hg38_splice_junctions.bed"
gencode_annotation: "${projectDir}/ref/gencode.v49.primary_assembly.annotation.gtf"
